In [24]:
import pandas as pd

In [25]:
temp = pd.read_csv("../data/raw/global_temp.csv")
co2 = pd.read_csv("../data/raw/co2.csv")
sea = pd.read_csv("../data/raw/sea_level.csv")

Temperature Dataset Cleaning

In [26]:
temp.head()
temp.info()
temp.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 577462 entries, 0 to 577461
Data columns (total 4 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   dt                             577462 non-null  str
 1   AverageTemperature             544811 non-null  float64
 2   AverageTemperatureUncertainty  545550 non-null  float64
 3   Country                        577462 non-null  str
dtypes: float64(2), str(2)
memory usage: 17.6 MB

dt                                   0
AverageTemperature               32651
AverageTemperatureUncertainty    31912
Country                              0
dtype: int64

In [27]:
temp['Year'] = pd.to_datetime(temp['dt'], errors='coerce').dt.year
temp = temp.dropna(subset=['AverageTemperature', 'Year'])
temp_clean = temp.groupby('Year')['AverageTemperature'].mean().reset_index()
temp_clean.rename(columns={'AverageTemperature': 'Temperature'}, inplace=True)

In [28]:
temp_clean.head()

   Year  Temperature
0  1743     5.184140
1  1744     9.837898
2  1745     1.387125
3  1750     9.129353
4  1751     9.167388

In [29]:
temp_clean.to_csv("../data/cleaned/temp_clean.csv", index=False)

CO2 Dataset Cleaning

In [30]:
co2.head()
co2.columns

Index(['country_code', 'country_name', 'year', 'value'], dtype='str')

In [31]:
co2 = co2[['year', 'value']]
co2.rename(columns={
    'year': 'Year',
    'value': 'CO2'
}, inplace=True)

In [32]:
co2 = co2.dropna()
co2_clean = co2.groupby('Year')['CO2'].mean().reset_index()

In [33]:
co2_clean.to_csv("../data/cleaned/co2_clean.csv", index=False)

SEA LEVEL DATASET CLEANING

In [34]:
sea.head()
sea.columns

Index(['year', 'date', 'mmfrom1993-2008average'], dtype='str')

In [35]:
sea.rename(columns={
    'year': 'Year',
    'mmfrom1993-2008average': 'SeaLevel'
}, inplace=True)

In [36]:
sea = sea.dropna(subset=['Year', 'SeaLevel'])
sea['Year'] = sea['Year'].astype(int)
sea['SeaLevel'] = sea['SeaLevel'].astype(float)

In [37]:
sea_clean = sea.groupby('Year')['SeaLevel'].mean().reset_index()
sea_clean = sea_clean.sort_values('Year')

In [38]:
sea_clean.head()

   Year    SeaLevel
0  1880 -183.247396
1  1881 -174.014062
2  1882 -190.080729
3  1883 -185.147396
4  1884 -166.280729

In [39]:
sea_clean.to_csv("../data/cleaned/sea_clean.csv", index=False)

In [40]:
sea_clean['SeaLevel_MA'] = sea_clean['SeaLevel'].rolling(5).mean()